UI tests
roguestroke/wtf pull request #3
Opened 2024-10-26 14:59 UTC by roguestroke

2024-11-11 01:40 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-11 01:40 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/BuildTypeTest.java
> +        CreateProjectPage.errorMessage.shouldHave(Condition.text("git -c credential.helper= ls-remote origin command failed.\n" + //
Отлично! Не хватает проверки на уровне API, что сущность не создалась.

2024-11-12 07:40 UTC, roguestroke commented on src/test/java/com/example/teamcity/ui/BuildTypeTest.java
> +        CreateProjectPage.errorMessage.shouldHave(Condition.text("git -c credential.helper= ls-remote origin command failed.\n" + //
Добавил.

2024-11-12 14:17 UTC, nobugs-me approved these changes

2024-11-12 14:17 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/BuildTypeTest.java
> +        CreateProjectPage.errorMessage.shouldHave(Condition.text("git -c credential.helper= ls-remote origin command failed.\n" + //
Спасибо!

2024-11-24 14:21 UTC, merged